server:
  port: 8080
  servlet:
    context-path: /

spring:
  # todo 개발 데이터베이스 연결
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver



  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true # 콘솔창에 sql 출력
    properties:
      hibernate:
        format_sql: true # sql 예쁘게 출력
        default_batch_fetch_size: 500 # 일대다 컬렉션 조회 시 성능 최적화
    open-in-view: false # 영속성 컨텍스트의 생존 범위를 트랜잭션 범위로 한정
  servlet:
    multipart:
      max-file-size: 10MB # 파일업로드 요청 시 하나의 파일 크기를 10MB로 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB로 제한
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    org.hibernate.type: trace # 콘솔창에 조건에 바인딩되는 값 및 조회 결과 출력
    com.app:  debug # todo 패키지 수정


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000


kakao:
  client:
    id: ENC(qzAEJk5UWWi92aoKGkHLTxgpQXFdGUj3/EVRLOf+QICRf7etP8WhCfg7Wm1U5Q+8)
    secret: ENC(c/NOqeMPADFhBOmqys0999CyeAewvKRxl3ROofk61v28OI5x9Yzvnt8WyE3rYwzb)

token:
  secret: ENC(0yLOx9P0MkwS60LS48CI22hC9gwAqYNDNuT3sCtxx5k23hjSG9lVsw==) # 임의의 문자열
  access-token-expiration-time: 900000 # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

jasypt:
  password: ${PASSWORD}